#!/usr/bin/env node

var fs = require('fs'),
    js2php = require('./index.js'),
    options = {};

while (/^-/.test(process.argv[2])) {
  if (process.argv[2]=="-v" || process.argv[2]=="--version") {
    console.warn(require('./package.json').version);
    return;
  } else if (process.argv[2]=="-n" || process.argv[2]=="--namespace") {
    options.namespace = process.argv[3];
    process.argv.shift(); process.argv.shift();
  } else if (process.argv[2]=='-w' || process.argv[2]=='--watermark') {
    options.watermark = process.argv[3];
    process.argv.shift(); process.argv.shift();
  } else if (process.argv[2]=='-b' || process.argv[2]=='--braced') {
    options.braced = true;
    process.argv.shift();
  } else {
    console.warn("Unknown option:", process.argv.shift());
  }
}
if (process.stdin.isTTY || process.argv.length > 2) {
  var result = js2php(fs.readFileSync(process.argv[2], 'utf8'), options);
  if (process.argv.length < 4) {
    console.log( result );
  } else {
    fs.writeFileSync(process.argv[3], result, 'utf8');
  }

} else {
  var code = "";
  process.stdin.resume();
  process.stdin.on('data', function(data) { code += data; });
  process.stdin.on('end', function() {
    console.log( js2php(code, options) );
  });
}
