#!/usr/bin/env node

var fs = require('fs'),
    js2php = require('./index.js');

if (process.stdin.isTTY) {

  if (process.argv[2]=="-v" || process.argv[2]=="--version") {
    console.log(require('./package.json').version);

  } else {
    console.log(  js2php(fs.readFileSync(process.argv[2]).toString()) );
  }

} else {
  var code = "";
  process.stdin.resume();
  process.stdin.on('data', function(data) { code += data; });
  process.stdin.on('end', function() {
    console.log( js2php(code) );
  });
}
